# Generated by Django 4.1.7 on 2023-04-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='points',
            field=models.IntegerField(max_length=200),
        ),
    ]
