# Generated by Django 4.1.7 on 2023-03-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fracciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primerNum', models.IntegerField(max_length=50)),
                ('primerDen', models.IntegerField(max_length=50)),
                ('segundoNum', models.IntegerField(max_length=50)),
                ('segundoDen', models.IntegerField(max_length=50)),
            ],
        ),
    ]
