# Generated by Django 4.1.7 on 2023-03-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fracciones',
            name='primerDen',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fracciones',
            name='primerNum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fracciones',
            name='segundoDen',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fracciones',
            name='segundoNum',
            field=models.IntegerField(),
        ),
    ]
