# Generated by Django 4.2.7 on 2024-01-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.IntegerField()),
                ('date', models.DateField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
