# Generated by Django 4.1.7 on 2023-04-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fracciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primerNum', models.IntegerField()),
                ('primerDen', models.IntegerField()),
                ('operador', models.CharField(default='+', max_length=1)),
                ('segundoNum', models.IntegerField()),
                ('segundoDen', models.IntegerField()),
                ('result', models.CharField(default='0', max_length=200)),
            ],
        ),
    ]
